Avanza #17. Documentación del gestor de tareas y gestor de dependenci…
gomares/More-mangas pull request #19
Opened 2021-11-26 16:18 UTC by gomares

…as elegidos.

Se añade documentación referente a la elección del gestor de tareas y el gestor de dependencias.

2021-11-26 16:33 UTC, gomares commented
Listo para revisión @JJ

2021-11-28 10:05 UTC, gomares commented
Ahora sí que sí, estoy mucho más tranquilo habiendo elegido PyFlakes. Todo el mundo usando Pylint y mira que no e sfácil de usar, uf. Listo para ser revisado.

2021-11-28 10:06 UTC, gomares commented
Caí ayer y pasé hasta mala noche por no corregirlo en ese mismo día JAJAJAJA.

2021-11-28 10:42 UTC, JJ commented
> Ahora sí que sí, estoy mucho más tranquilo habiendo elegido PyFlakes. Todo el mundo usando Pylint y mira que no e sfácil de usar, uf. Listo para ser revisado.

Pero es que no tienen que usar ningún comprobador estátito de código, sólo si compila o no. Pero si eso te tranquiliza...

2021-11-28 10:42 UTC, JJ commented
> Caí ayer y pasé hasta mala noche por no corregirlo en ese mismo día JAJAJAJA.

Ese es el espíritu de los grandes ingenieros de software :+1:

2021-11-28 10:47 UTC, JJ requested changes
En general está bien, pero dale una vueltecilla.

2021-11-28 10:47 UTC, JJ commented on README.md
> +# More Mangas!
Ya puestos podías haber cambido también el nombre del repo

2021-11-28 10:47 UTC, JJ commented on README.md
> +pip install invoke
Primero deberías instalar un gestor de dependencias que no sea pip, porque `requirements.txt` no se debe usar en desarrollo a estas alturas. También dicho muchas veces en clase.

2021-11-28 10:47 UTC, JJ commented on README.md
> +poetry install
Si instalas poetry, úsalo para instalar invoke (porque será parte de las dependencias)

2021-11-28 10:47 UTC, JJ commented on code/manga.py
> +from errors import GenreNotFound, MangakaTypeError
Si usas `-Error` al final de las excepciones, úsalo siempre. Hay que ser consistente en los identificadores.

2021-11-28 10:47 UTC, JJ commented on docs/objetivo-3.md
> +Las dos opciones principales eran Invoke y Poetry.
Poetry no es un gestor de tareas, es un gestor de dependencias que puede hacer algunas tareas. Y no son las opciones principales. Por favor, buscad un poco, que sólo en clase hay como 3 o 4 más.

2021-11-28 10:47 UTC, JJ commented on docs/objetivo-3.md
> +El proyecto usará Invoke como task manager debido a su completitud y simplicidad. Aunque Poetry es incluso más simple, tiene la pega de que su enfoque está dirigido más a la gestión de dependencias y
O sea, que comparas un gestor de tareas con otro que no lo es y te quedas con el gestor de tareas para gestionar tareas... Por favor, mirad un poco más y haced las justificaciones técnicas como lo hemos dicho en clase.

2021-11-28 10:47 UTC, JJ commented on docs/objetivo-3.md
> +Por todo lo mencionado anteriormente, se ha elegido Invoke pues me parece que se adecua mejor como gestor de tareas.
Igual es porque es un gestor de tareas y el otro no.

2021-11-28 10:47 UTC, JJ commented on pyproject.toml
> +pyflakes = "^2.4.0"
¿Seguro que no es `dev`?

2021-11-28 11:46 UTC, gomares commented on README.md
> +# More Mangas!
Profesor al cambiar a More Mangas! me pone un guión al final en vez de la exclamación ¿hay alguna forma de sortear ese formateo?, si no, lo puedo dejar así.

2021-11-28 12:26 UTC, gomares commented
Le he echado un vistazo a todo lo que me dijo y he mirado algunas verdaderas alternativas al task runner que usamos y al dependencies manager.

2021-11-28 12:27 UTC, gomares commented
Listo para ser revisado @JJ. Gracias por haberme corregido rápido :)

2021-11-28 18:50 UTC, JJ approved these changes
:+1:

2021-11-28 18:50 UTC, JJ commented on README.md
> +# More Mangas!
Convierte a guión lo que no es ASCII como el !. Simplemente cámbialo de nuevo y borra el guión.

2021-11-28 18:50 UTC, JJ commented on docs/objetivo-3.md
> +He elegido Poetry porque su página de docuemtnación no podría estar más completa, su sintaxis es increíblemente sencilla más que pipenv y que hatch. Hatch tiene incluso más aspectos reflejados en el
typo :pencil2:

2021-11-29 07:32 UTC, merged