[IV-21-22] Objetivo 4
gomares/More-mangas pull request #30
Opened 2021-12-09 20:51 UTC by gomares

Se desarrollan aspectos fundamentales de la aplicación y la lógica de negocio para ser testeados con un gestor.
Trabaja sobre los issues #21, #22, #23, #24, #25, #26, #27, #28, #29

2021-12-09 21:40 UTC, gomares commented
Los tests funcionan correctamente, la lógica implementada aunque es básica pero es funcional.

2021-12-09 21:47 UTC, gomares commented
Listo para revisión @JJ. Al final tardé me tiré toda la tarde, lo siento. Tuve que llevar a mi perrilla al veterinario porque se ha puesto muy mala :(

2021-12-10 08:25 UTC, JJ requested changes
El milestone al que lo has añadido no tiene nada que ver con esta funcionalidad, ni incluye esto como PMV, ni especifica cómo se va a considerar viable. Aparte que no tengo muy claro qué estás haciendo con la lógica de negocio, ni cómo estás teniendo en cuenta las preferencias del usuario en las recomendaciones.

2021-12-10 08:25 UTC, JJ commented on docs/objetivo-4.md
> +Las posibles opciones eran Robot(el más popular), PyTest, UnitTest y DocTest. Robot a pesar de ser muy completo tenía demasiadas funcionalidades que no se le darán uso en este proyecto y DocTest pres
Los criterios tenéis que establecerlos de antemano. Y por lo menos enlazar lo que decís. Unittest no es un gestor de tests.

2021-12-10 08:25 UTC, JJ commented on docs/objetivo-4.md
> +El software elegido para realizar los tests, será la librería PyTest. Tiene una sintaxis muy sencilla (no como DocTest por ejemplo) y se invoca de manera sencilla también, presenta buena documentació
No se trata de que me comuniquéis la decisión, sino que mostréis que sabéis elegir una herramienta.

2021-12-10 08:25 UTC, JJ commented on docs/objetivo-4.md
> +Las posibles opciones eran Grappa, Asssertpy y Verify. Verify decidí descartarlo puesto que la última actualización era de 2017 y no parecía haber demasiado trabajo en el proyecto por parte de los pr
¿Y UnitTest? ¿Qué hace UnitTest?

2021-12-10 08:25 UTC, JJ commented on docs/objetivo-4.md
> +
Los criterios tienes que establecerlos de antemano.

2021-12-10 08:25 UTC, JJ commented on docs/objetivo-4.md
> +Las posibles opciones eran Robot(el más popular), PyTest, UnitTest y DocTest. Robot a pesar de ser muy completo tenía demasiadas funcionalidades que no se le darán uso en este proyecto y DocTest pres
Unittest y Pytest no son comparables. Enlaza de lo que estás hablando. Y tratad de entender lo que os pido, no os limitéis a copiar lo que dice no sé qué artículo.

2021-12-10 08:25 UTC, JJ commented on manga/genre.py
> +ponderacion = {Genre.SHONEN: 7, Genre.SEINEN: 5, Genre.SHOJO: 7, Genre.JOSEI: 10, Genre.KODOMO: 4, Genre.ISEKAI: 7,
¿Esto está justificado en alguna HU?

2021-12-10 08:25 UTC, JJ commented on manga/manga.py
> +            l.append(genre)
¿No puedes usar Genre directamente? Si lo vas a usar como lista, ¿por qué no lo declaras como lista?

2021-12-10 08:25 UTC, JJ commented on manga/recomendaciones.py
> +        recom_finales = recom_finales[0:3] #Sacamos nuestro top 3
¿Dónde tienes en cuenta al usuario? Sólo usas esa variable para ver si la longitud es cero.

2021-12-10 08:25 UTC, JJ commented on tests/test_recomendaciones.py
> +]
Esto sería mejor que fuera un fichero JSON externo.

2021-12-10 08:52 UTC, gomares commented on manga/recomendaciones.py
> +        recom_finales = recom_finales[0:3] #Sacamos nuestro top 3
Trabajo en el caso de un nuevo lector que se le dan recomendaciones generales pero que se calculan con la puntuación media de los usuarios de la aplicación, la ponderación de sus géneros y el número de vólumenes que puede especificar el user (por si quiere mangas cortos o algo como One Piece). El caso del lector experto (que tiene mangas leídos lo trataré un poco más adelante).

2021-12-10 10:19 UTC, JJ commented
> Listo para revisión @JJ. Al final me tiré toda la tarde, lo siento. Tuve que llevar a mi perrilla al veterinario porque se ha puesto muy mala :(

Vaya, espero que esté mejor ahora.

2021-12-11 12:51 UTC, gomares commented
Listo para revisión @JJ. 😄

2021-12-11 12:52 UTC, gomares commented on manga/genre.py
> +ponderacion = {Genre.SHONEN: 7, Genre.SEINEN: 5, Genre.SHOJO: 7, Genre.JOSEI: 10, Genre.KODOMO: 4, Genre.ISEKAI: 7,
Sii en #25.

2021-12-12 09:18 UTC, JJ approved these changes
OK, vamos a suponer que el milestone incluye este código, aunque realmente no lo parece. En el siguiente trata de ser un poco más preciso con eso.

2021-12-12 09:18 UTC, JJ commented on manga/genre.py
> +ponderacion = {"SHONEN": 7, "SEINEN": 5, "SHOJO": 7, "JOSEI": 10, "KODOMO": 4, "ISEKAI": 7,
Sería mejor que géneros lo extrayeras como las claves de este diccionario. Si no, tendrás que modificar en dos sitios.

2021-12-12 09:57 UTC, merged