[IV-21-22]  Objetivo 6
gomares/More-mangas pull request #40
Opened 2021-12-21 17:06 UTC by gomares

En este Pull Request se han trabajado en los siguientes contenidos con el objetivo de superar el objetivo 6:

- Elección de dos sistemas de integración continua.

- Justificación de los sistemas de CI elegidos.

- Configuración de los sistemas de CI y justificación para pasar los tests automáticamente al hacer push al repositorio y comprobar las versiones del lenguaje con las que funciona el proyecto.

Se ha trabajado en las issues:

- Sistemas de Integración continua #34 .

- Configuración de los sistemas de integración continua #35 .

- Añadir Sistemas de integración continua a iv.yaml #36 .

2021-12-22 08:02 UTC, JJ requested changes
Aparte de lo dicho en privado, tienes que darle una vuelta a esto.

2021-12-22 08:02 UTC, JJ commented on .github/workflows/update_docker.yml
> +      - 'main'
¿Sólo se actualiza en main?

2021-12-22 08:02 UTC, JJ commented on .github/workflows/continous_integration.yml
> +name: Docker Image CI
Podías llamarlo de otra forma...

2021-12-22 08:02 UTC, JJ commented on .github/workflows/continous_integration.yml
> +    branches: [ main ]
Por favor, mirad bien qué significa lo de las branches. No lo va a pasar en un PR, por ejemplo.

2021-12-22 09:01 UTC, gomares commented on .github/workflows/update_docker.yml
> +      - 'main'
Voy a realizar cambios para que no solo se actualice en main si no en las ramas pertencientes a objetivos de la asignatura.

2021-12-22 09:02 UTC, gomares commented on .github/workflows/continous_integration.yml
> +name: Docker Image CI
Voy a pensar en un título más apropiado para lo que hago.

2021-12-22 09:02 UTC, gomares commented on .github/workflows/continous_integration.yml
> +    branches: [ main ]
Cierto.

2021-12-22 09:05 UTC, gomares commented
Cambios realizados.

2021-12-29 19:27 UTC, JJ commented
Revisores → @jesusmarzor @amerigal @modejota

2022-01-05 12:00 UTC, amerigal reviewed
Muy completo y trabajado el objetivo :1st_place_medal: 

Solo hacer unas observaciones. Por un lado, con respecto a los workflows de github actions, si vas a incluir todas las ramas diría que no es necesario que incluyas la condición de branches. Además, me da la impresión de que tal y como está, los workflows se están ejecutando dos veces, una vez por ser un push a una rama del tipo Objetivo-* y otra por tratarse de un pull request a main. No estoy del todo seguro, porque aparecen muchos tests ejecutados y lo mismo es por otra cosa, pero por si puedes revisar eso para no hacer ejecuciones innecesasarias.

2022-01-05 12:00 UTC, amerigal commented on .circleci/config.yml
> +              version: ["3.8","3.9","3.10"]
Creo que sería interesante una justificación de por qué son esas las versiones que se están testeando.

2022-01-05 12:30 UTC, modejota commented on .circleci/config.yml
> +              version: ["3.8","3.9","3.10"]
Same here, aunque viendo que el 99% de los proyectos lo utilizan, me hago una idea

2022-01-05 12:36 UTC, modejota commented
Por mi parte, 3/4 lo mismo que comenta @amerigal.
- Si especificas que se lance en los push y pull request puede que se ejecute dos veces innecesariamente, que tampoco sé si realmente pasa así. En mis pruebas los puse en una u otra cosa, pero no en ambas.
- Si especificas que se lance en "main" y "Objetivo-*", básicamente lo estamos lanzando siempre, ya que no utilizamos otros nombres de rama, por lo que casi que no es necesario especificarlo.
- Justificar un poco porque se utiliza cada versión. Puedo intuir que 3.8 por que será la mínima que soporte alguna funcionalidad concreta, 3.10 por ser la más reciente, y 3.9 porque sí.

2022-01-07 06:35 UTC, JJ commented
⛹ Revisores → @amerigal @paula1999 @Olasergiolas

2022-01-08 17:50 UTC, Olasergiolas requested changes
En general lo veo bien, aunque creo que deberías concretar algo más lo que has hecho para el objetivo en el PMV, además de que por ejemplo dices que solo se incorpora un sistema de integración. Échale un vistazo también a un par de fallos tontos que te he comentado 👍.

2022-01-08 17:50 UTC, Olasergiolas commented on docs/objetivo-6.md
> +* En segundo lugar descarté **SempahoreCI** por la misma razón que Travis, exigen que pagues pasados [14 días](https://semaphoreci.com/pricing). Además de esto no es tan popular como otras opciones d
No usaría "popular" para la justificación sino las consecuencias que tiene el que sea más popular, es decir, podrías poner en su lugar que tiene una mayor comunidad o que problemas comunes con la plataforma están mejor documentados.

2022-01-08 17:50 UTC, Olasergiolas commented on docs/objetivo-6.md
> +* Las dos últimas opciones que investigué eran por un lado **Jenkins** y por otro **CircleCI**. Jenkins presentaba unos [problemas](https://circleci.com/migrate-jenkins-to-circleci/) que CircleCI no,
Typo en "cause".

2022-01-08 17:50 UTC, Olasergiolas commented on docs/objetivo-6.md
> +* Las dos últimas opciones que investigué eran por un lado **Jenkins** y por otro **CircleCI**. Jenkins presentaba unos [problemas](https://circleci.com/migrate-jenkins-to-circleci/) que CircleCI no,
Enlace markdown "editar tu archivo config.yml" roto.

2022-01-08 17:50 UTC, Olasergiolas commented on .github/workflows/continous_integration.yml
> +name: Docker from DockeHub run tests
Typo en "DockeHub".

2022-01-10 11:51 UTC, gomares commented on docs/objetivo-6.md
> +* Las dos últimas opciones que investigué eran por un lado **Jenkins** y por otro **CircleCI**. Jenkins presentaba unos [problemas](https://circleci.com/migrate-jenkins-to-circleci/) que CircleCI no,
Arreglado

2022-01-10 11:51 UTC, gomares commented on docs/objetivo-6.md
> +* Las dos últimas opciones que investigué eran por un lado **Jenkins** y por otro **CircleCI**. Jenkins presentaba unos [problemas](https://circleci.com/migrate-jenkins-to-circleci/) que CircleCI no,
Corregida

2022-01-10 12:01 UTC, gomares commented on docs/objetivo-6.md
> +* En segundo lugar descarté **SempahoreCI** por la misma razón que Travis, exigen que pagues pasados [14 días](https://semaphoreci.com/pricing). Además de esto no es tan popular como otras opciones d
Sí, tienes razón. SemaphoreCI la descarté por tener versión de pago y una documentación peor que la de Travis, este me pareció la opción a usar si estaba dispuesto a pagar.

2022-01-10 12:02 UTC, gomares commented on .github/workflows/continous_integration.yml
> +name: Docker from DockeHub run tests
Corregida

2022-01-10 16:11 UTC, gomares commented on .circleci/config.yml
> +              version: ["3.8","3.9","3.10"]
Ya he dejado una justificación, muchas gracias chicos. En el objetivo 5 también hablé acerca de por qué incluí la nueva versión de Python. 😄

2022-01-10 16:15 UTC, gomares commented
Estuve investigando las branches y los pushes y pull requests como eventos de workflows y ya he cambiado los ficheros de los workflows para que ahora solo se ejecute una vez los tests y no dos como antes hacía. @amerigal @modejota . Muchas gracias por la aportación.

He mejorado algunas cosillas que me indicaste @Olasergiolas, gracias a ti también 😄 .
También he corregido lo que me dijo el profesor en su día cuando tenía problemas para añadirme revisores jejeje.

Creo que está todo en orden, si me dais algo más de feedback lo pongo como listo para revisión.

2022-01-10 17:23 UTC, amerigal commented
> Estuve investigando las branches y los pushes y pull requests como eventos de workflows y ya he cambiado los ficheros de los workflows para que ahora solo se ejecute una vez los tests y no dos como antes hacía. @amerigal @modejota . Muchas gracias por la aportación.
> 
> He mejorado algunas cosillas que me indicaste @Olasergiolas, gracias a ti también smile . También he corregido lo que me dijo el profesor en su día cuando tenía problemas para añadirme revisores jejeje.
> 
> Creo que está todo en orden, si me dais algo más de feedback lo pongo como listo para revisión.

Veo bien los cambios realizados :+1:. Lo único que no me termina de convencer de esa parte es la justificación de que se usara la versión 3.7 inicialmente porque es la que estaba instalada en el ordenador. Pienso que las justificaciones deben ir más bien enfocadas a las necesidades del proyecto.

Lo último comentar sobre los issues y el milestone. Entiendo que sería apropiado que los issues introducidos se refirieran directa o indirectamente a HUs, y que esas HUs a cuya consecución están contribuyendo los issues se incluyeran también en el milestone.

2022-01-10 18:06 UTC, gomares commented
La historia creada no era necesaria, tenía #34 ya así que voy a reescribir algunas cosas para que guarden relación entre sí. A ver si logro lo que dices @amerigal .

2022-01-10 18:25 UTC, gomares commented
Ya está corregido @amerigal.

2022-01-10 18:26 UTC, Olasergiolas approved these changes
Por mi parte creo también que ya es suficiente para pasar el objetivo.

2022-01-10 18:36 UTC, amerigal approved these changes
Todo en orden por mi parte :+1:

2022-01-10 18:38 UTC, gomares commented
Perfecto, pues gracias por vuestras revisiones. Por mi parte lo veo listo para revisión @JJ. 😃

2022-01-10 19:23 UTC, JJ commented on .github/workflows/update_docker.yml
> +      - 'main'
¿En main no?

2022-01-10 19:23 UTC, JJ commented on .github/workflows/continous_integration.yml
> +name: Docker Image CI
... y el nombre del fichero...

2022-01-10 19:29 UTC, JJ requested changes
En este objetivo se busca que sepáis buscar y elegir el sistema de CI más adecuado a vuestro proyecto, estableciendo criterios sólidos para los mismos. También que sepáis testear diferentes versiones y por qué lo hacéis No has justificado las versiones de Python empleadas, y no has justificado por qué eliges esos dos sistemas, sólo a posteriori. Me temo que no superas el objetivo.

2022-01-10 19:29 UTC, JJ commented on .github/workflows/run_tests_in_test_container.yml
> +        run: docker run -t -v `pwd`:/app/test gomares/more-mangas
¿Qué versión testa este?

2022-01-10 19:29 UTC, JJ commented on docs/objetivo-6.md
> +Se necesitan dos servicios de integración continua para cumplir el hito. Se han valorado ciertos CIs:
Lo primero que hay que poner son los criterios de elección. Si se han "valorado", tienes que decir en qué se basa. ¿Están recomendados como las mejores prácticas en algún artículo?

2022-01-10 19:29 UTC, JJ commented on docs/objetivo-6.md
> +* En segundo lugar descarté **SempahoreCI** por la misma razón que Travis, exigen que pagues pasados [14 días](https://semaphoreci.com/pricing). Además de esto no tiene una comunidad tan grande como
Razón que tenías que haber establecido de antemano.

2022-01-10 19:29 UTC, JJ commented on docs/objetivo-6.md
> +Elegí CircleCI y GH Actions para la realización del objetivo. Por tanto, se han configurado dos tareas relativas a la Integración Continua:
Como el 99% de la clase. Y por las mismas razones: son lo que habías decidido desde el principio.

2022-02-04 10:50 UTC, gomares commented on .github/workflows/run_tests_in_test_container.yml
> +        run: docker run -t -v `pwd`:/app/test gomares/more-mangas
La 3.10, lo especifique cuando se creó el contenedor en objetivos anteriores, aclararé esto en la neuva documentación.

2022-02-04 10:50 UTC, gomares commented on docs/objetivo-6.md
> +Se necesitan dos servicios de integración continua para cumplir el hito. Se han valorado ciertos CIs:
Pondré criterios preliminares en la nueva documentación. Gracias por la ayuda.

2022-02-07 18:33 UTC, JJ commented
⛹ Revisores → @morevi @Pablont98 @lentes4k

2022-02-07 18:45 UTC, gomares commented
Listo para revisión @JJ. No creo que nadie quiera revisarlo 😢

2022-02-10 13:38 UTC, JJ commented on docs/objetivo-6.md
> +* En segundo lugar descarté **SempahoreCI** por la misma razón que Travis, exigen que pagues pasados [14 días](https://semaphoreci.com/pricing). Además de esto no tiene una comunidad tan grande como
... aparte de escribirlo correctamente.

2022-02-10 13:43 UTC, JJ approved these changes
:+1: porque has probado un montón de sistemas de CI. Pero la versión sigue siendo incorrecta, y podrías haber establecido algún criterio restrictivo de antemano.

2022-02-10 13:43 UTC, JJ commented on .appveyor.yml
> +image: Ubuntu
Tercer fichero que me encuentro para exactamente el mismo sistema de CI y con prácticamene las mismas órdenes. CircleCI no es malo de por si, es malo porque al haberlo usado ya n personas, la persona n+1 no tenía más que copiarlo. Se trata de que aprendáis y entendáis lo que estás haciendo, no de que pongáis n sitios de integración continua.

2022-02-13 09:49 UTC, merged